apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: foo
  namespace: foo
spec:
  exportTo:
  - workspaces:
    - name: ops-team
  importFrom:
  - workspaces:
    - name: ops-team
  options:
    serviceIsolation:
      enabled: true
      trimProxyConfig: true
