apiVersion: admin.gloo.solo.io/v2
kind: Workspace
metadata:
  name: gh-action-idp
  namespace: gloo-mesh
  labels:
    allow_ingress: "true"
spec:
  workloadClusters:
  - name: '*'
    namespaces:
    - name: gh-action-idp