apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: blanket-route
  namespace: gh-action-idp
spec:
  hosts:
    - 'blanket.demo.glooplatform.com'
  virtualGateways:
    - name: mgmt-north-south-gw-443
      namespace: istio-gateways
      cluster: mgmt
  workloadSelectors: []
  http:
    - name: blanket
      matchers:
        - uri:
            prefix: /anything
      forwardTo:
        destinations:
          - ref:
              name: httpbin
              namespace: gh-action-idp
            port:
              number: 8000
