apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: foo-parent
  namespace: ops-team-config
spec:
  hosts:
    - 'foo.demo.glooplatform.com'
  virtualGateways:
    - name: mgmt-north-south-gw-443
      namespace: istio-gateways
      cluster: mgmt
  http:
    - name: foo-team-a
      matchers:
        - uri:
            prefix: /team-a
      delegate:
        routeTables:
          - labels:
              workspace: foo
              team: team-a
    - name: foo-team-b
      matchers:
        - uri:
            prefix: /team-b
      delegate:
        routeTables:
          - labels:
              workspace: foo
              team: team-b
