apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: gh-action-idp-team-a-httpbin-delegate
  namespace: gh-action-idp
  labels:
    workspace: gh-action-idp
    team: team-a
spec:
  defaultDestination:
    port:
      number: 8000
    ref:
      name: httpbin
      namespace: gh-action-idp
  http:
  - name: team-a-root
    matchers:
    - uri:
        prefix: /
    forwardTo:
      pathRewrite: /
