apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: gh-action-idp-swagger-ui-rt-443
  namespace: portal
spec:
  hosts:
    - 'idp.demo.glooplatform.com'
  virtualGateways:
    - name: mgmt-north-south-gw-443
      namespace: istio-gateways
      cluster: mgmt
  workloadSelectors: []
  http:
    - name: gh-action-idp-swagger-ui
      matchers:
      - uri:
          prefix: /
      - uri:
          prefix: /callback
      forwardTo:
        destinations:
        - ref:
            name: gh-action-idp-swagger-ui
            namespace: portal
          port:
            number: 80
