apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: gh-action-idp-b-delegate
  namespace: gh-action-idp
  labels:
    workspace: gh-action-idp
    team: b
spec:
  defaultDestination:
    port:
      number: 8000
    ref:
      name: httpbin
      namespace: gh-action-idp
  http:
  - name: b-get
    matchers:
    - uri:
        prefix: /get
    forwardTo:
      pathRewrite: /get
  - name: b-ip
    matchers:
    - uri:
        prefix: /ip
    forwardTo:
      pathRewrite: /ip
