apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: gh-action-idp-delegate
  namespace: gh-action-idp
  labels:
    workspace: gh-action-idp
spec:
  http:
  - name: gh-action-idp-delegate
    matchers:\n    - uri:\n        prefix: /get\n    - uri:\n        prefix: /anything
    forwardTo:
      destinations:
      - ref:
          name: httpbin
          namespace: gh-action-idp
        port:
          number: 8000
