apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: gh-action-idp-team-b-delegate
  namespace: gh-action-idp
  labels:
    workspace: gh-action-idp
    team: team-b
spec:
  defaultDestination:
    port:
      number: 8000
    ref:
      name: httpbin
      namespace: gh-action-idp
  http:
  - name: team-b-ip
    matchers:
    - uri:
        prefix: /ip
    forwardTo:
      pathRewrite: /ip
