apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: gh-action-idp-team-a-delegate
  namespace: team-a
  labels:
    workspace: gh-action-idp
    team: team-a
spec:
  defaultDestination:
    port:
      number: 8000
    ref:
      name: httpbin
      namespace: team-a
  http:
  - name: team-a-get
    matchers:
    - uri:
        prefix: /get
    forwardTo:
      pathRewrite: /get
