apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: gh-action-idp-gh-action-idp-team-a-delegate
  namespace: gh-action-idp
  labels:
    workspace: gh-action-idp
spec:
  defaultDestination:
    port:
      number: 8000
    ref:
      name: httpbin
      namespace: gh-action-idp
  http:
  - name: team-a-matcher1
    matchers:
    - uri:
        prefix: /get
    forwardTo:
      pathRewrite: /get
  - name: team-a-matcher2
    matchers:
    - uri:
        prefix: /ip
    forwardTo:
      pathRewrite: /ip
