apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: "{{ .Values.app.name }}"
    tier: "{{ .Values.app.tier }}"  # Ensure tier is treated as a string
