apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-service-team-b
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
  source:
    repoURL: 'https://github.com/ably77/gh-action-idp'
    targetRevision: HEAD
    path: sample-service-helm-chart
    helm:
      values: |
        namespace: team-b

        istio:
          revision: "1-22"

        app:
          name: sample-service-team-b
          tier: "1"
          replicas: 1
          image:
            repository: nicholasjackson/sample-service
            tag: v0.26.2

        service:
          port: 8080
          targetPort: 8080

        env:
          LISTEN_ADDR: "0.0.0.0:8080"
          NAME: "sample-service-team-b"
          SERVER_TYPE: "http"
          MESSAGE: "Hello From sample-service-team-b !"
          UPSTREAM_URIS: ""
          UPSTREAM_WORKERS: "1"
          TIMING_50_PERCENTILE: "0ms"
          TIMING_90_PERCENTILE: "0ms"
          TIMING_99_PERCENTILE: "0ms"
          HTTP_CLIENT_REQUEST_TIMEOUT: "1s"
          HTTP_SERVER_KEEP_ALIVES: "true"
          HTTP_CLIENT_KEEP_ALIVES: "true"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
