name: Create Workspace Action

on:
  workflow_dispatch:
    inputs:
      workspace_name:
        description: 'The name of the Workspace'
        required: true
        type: string
      namespaces:
        description: 'Comma-separated list of namespaces to include in the Workspace'
        required: true
        type: string

permissions:
  contents: write

jobs:
  create-workspace-manifests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Create an empty branch
        id: create_branch
        run: |
          BRANCH_NAME="workspace-update-${{ github.run_id }}-${{ github.event.inputs.workspace_name }}"
          git checkout --orphan $BRANCH_NAME
          git rm -rf .
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Render Workspace and WorkspaceSettings manifests based on input
        id: render_manifests
        run: |
          WORKSPACE_NAME=${{ github.event.inputs.workspace_name }}
          NAMESPACES=${{ github.event.inputs.namespaces }}

          WORKSPACE_FILE_PATH="mesh-admin/${WORKSPACE_NAME}-workspace.yaml"
          WORKSPACE_SETTINGS_FILE_PATH="mesh-admin/${WORKSPACE_NAME}-workspacesettings.yaml"

          mkdir -p mesh-admin

          # Split the comma-separated namespaces into a YAML array format
          NAMESPACE_YAML=$(echo "$NAMESPACES" | sed 's/,/\\n- name: /g')
          NAMESPACE_YAML="- name: ${NAMESPACE_YAML}"

          cat <<EOF > $WORKSPACE_FILE_PATH
          apiVersion: admin.gloo.solo.io/v2
          kind: Workspace
          metadata:
            name: ${WORKSPACE_NAME}
            namespace: gloo-mesh
          spec:
            workloadClusters:
            - name: '*'
              namespaces:
                ${NAMESPACE_YAML}
          EOF

          cat <<EOF > $WORKSPACE_SETTINGS_FILE_PATH
          apiVersion: admin.gloo.solo.io/v2
          kind: WorkspaceSettings
          metadata:
            name: ${WORKSPACE_NAME}
            namespace: ${WORKSPACE_NAME}
          spec:
            exportTo:
            - workspaces:
              - name: ops-team
            importFrom:
            - workspaces:
              - name: ops-team
            options:
              serviceIsolation:
                enabled: true
                trimProxyConfig: true
          EOF

          echo "WORKSPACE_FILE_PATH=$WORKSPACE_FILE_PATH" >> $GITHUB_ENV
          echo "WORKSPACE_SETTINGS_FILE_PATH=$WORKSPACE_SETTINGS_FILE_PATH" >> $GITHUB_ENV

      - name: Commit and push changes
        run: |
          git add ${{ env.WORKSPACE_FILE_PATH }} ${{ env.WORKSPACE_SETTINGS_FILE_PATH }}
          git commit -m "Add new Workspace and WorkspaceSettings for workspace ${{ github.event.inputs.workspace_name }}"
          git push origin ${{ env.BRANCH_NAME }}

      - name: Merge branch into main
        run: |
          git fetch origin main
          git checkout main
          git pull origin main
          git merge --allow-unrelated-histories --no-ff ${{ env.BRANCH_NAME }}
          git push origin main || (git pull --rebase origin main && git push origin main)

      - name: Delete branch after merge
        run: |
          git push origin --delete ${{ env.BRANCH_NAME }}
